basePath: /Student_Management_System
definitions:
  common.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  common.RegisterRequest:
    properties:
      password:
        type: string
      student_id:
        type: string
      username:
        type: string
    type: object
  course_handler.tableResponse:
    properties:
      course_list:
        items:
          $ref: '#/definitions/system.CourseInfo'
        type: array
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  navigate_handler.NavigateResponse:
    properties:
      node_list:
        items:
          items:
            type: number
          type: array
        type: array
      path_list:
        items:
          $ref: '#/definitions/system.PathGuider'
        type: array
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  system.CourseInfo:
    properties:
      classroom:
        description: 线下课程记录教室, 线上课程记录会议链接
        type: string
      contact:
        type: string
      course_id:
        type: integer
      course_location_node:
        description: 对应导航地图的节点, 设置成数组是因为一个地点可能对应多个node
        items:
          type: integer
        type: array
      course_name:
        type: string
      exam_location:
        type: string
      exam_location_node:
        items:
          type: integer
        type: array
      exam_option:
        type: integer
      exam_time:
        description: 考试时间, 格式为'第几周-星期几-几点~几点（HH:mm~HH:mm）', 如'第十六周-星期三-19:00~20:00'
        type: string
      is_course_online:
        type: boolean
      section_list:
        items:
          type: integer
        type: array
      teacher:
        type: string
      week_schedule:
        items:
          type: integer
        type: array
    type: object
  system.PathGuider:
    properties:
      distance:
        description: 向量长度,单位为米
        type: number
      heading:
        description: 向量方向,用航向角来计算(正北为0,360等分)
        type: integer
    type: object
  user_handler.loginResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      token:
        type: string
      user_id:
        type: integer
    type: object
  user_handler.registerResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      token:
        type: string
      user_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A application for Data Structure Lesson
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Student Management System API
  version: alpha 1.0
paths:
  /course/table:
    get:
      description: 获取学生所有的课程表信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/course_handler.tableResponse'
      security:
      - ApiKeyAuth: []
      summary: 课程表
      tags:
      - 课程表相关接口
  /navigate/path:
    get:
      consumes:
      - application/json
      description: 获取导航路线
      parameters:
      - description: 起始节点ID
        in: query
        name: from_id
        required: true
        type: integer
      - description: 结束节点ID
        in: query
        name: des_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/navigate_handler.NavigateResponse'
      security:
      - ApiKeyAuth: []
      summary: 导航
      tags:
      - 导航功能
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户信息
        in: body
        name: user_input
        required: true
        schema:
          $ref: '#/definitions/common.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_handler.loginResponse'
      summary: 登录
      tags:
      - 用户鉴权
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 用户信息
        in: body
        name: user_input
        required: true
        schema:
          $ref: '#/definitions/common.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_handler.registerResponse'
      summary: 注册
      tags:
      - 用户鉴权
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
